[package]
name = "challenge_3_break_xor"
version = "0.1.0"
authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2021"

[[bin]]
name = "break_xor"
path = "src/main.rs"

[dependencies]
hex = { version = "0.4.3" }
crypto_helper = {path = "../crypto_helper", version = "0.1.0"}
